####
#PUT http://localhost:8080/container/2/palette/1
#Content-Type: application/json
#
#{
#
#}

####

POST http://localhost:8080/palette
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJoaSIsInJvbGVzIjpbbnVsbF0sImlhdCI6MTY4NTg5MTQwMiwiZXhwIjoxNjg1ODkyMDAyfQ.LhGzrOll0vlAfIdk3aT2LL5ivFbssher0Znh977-bwU

{
  "pName": "Why",
  "quantity": 120,
  "height": 20.0,
  "weight": 20.0,
  "dLine": "2023-05-24T14:56:20.669",
  "firstDel": "경기도",
  "finalDel": "수원시 장안구"
}

####
GET http://localhost:8080/palette?dLineFrom=2023-05-23T00:00:20&dLineTo=2023-05-23T23:59:00
Accept: application/json

####
GET http://localhost:8080/palette?pName=h
Accept: application/json

####
GET http://localhost:8080/palette?paletteId=2
Accept: application/json

####
GET http://localhost:8080/palette?firstDel=경기도
Accept: application/json

####
POST http://localhost:8080/account/signin
Content-Type: application/json

{
  "userId" : "hi",
  "password" : "0"
}

####
GET http://localhost:8080/palette?containerId=1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJzb3JyeSIsInJvbGVzIjpbXSwiaWF0IjoxNjg1ODc1MjUyLCJleHAiOjE2ODU4NzU4NTJ9.IvBfmJgbQyZ6NlxJm2veTtZYr1Jk1oMMNdiHIGE7cr8


####
POST http://localhost:8080/container
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJzb3JyeSIsInJvbGVzIjpbXSwiaWF0IjoxNjg1ODczNDUyLCJleHAiOjE2ODU4NzQwNTJ9.oGcDjn8_dMZHzYUnguOp-N3hkR8uKSHZoMMgO99b7Bc

{
  "releaseDate" : "2023-05-29T02:19",
  "weight" : 10.0,
  "weightLimit" : 300.0
}


####
GET http://localhost:8080/container?releaseDateFrom=2023-05-28T01:10:00&releaseDateTo=2023-06-03T03:20:00
Accept: application/json

####
GET http://localhost:8080/container?releaseDateFrom=2023-06-02T01:10:00&releaseDateTo=2023-06-02T03:20:00
Accept: application/json

####
POST http://localhost:8080/account/signup
Content-Type: application/json

{
  "userId" : "hi",
  "password" : "0",
  "adName" : "이영진",
  "department" : "물류팀",
  "position" : "대리",
  "admCall" : "01012345678",
  "roles" : "ROLE_USER"
}

####
POST http://localhost:8080/account/signup
Content-Type: application/json

{
  "userId" : "bye",
  "password" : "1",
  "adName" : "이진영",
  "department" : "품질관리팀",
  "position" : "과장",
  "admCall" : "01087654321",
  "roles" : "ROLE_ADMIN"
}

####
POST http://localhost:8080/account/signup
Content-Type: application/json

{
  "userId" : "thank",
  "password" : "2",
  "rep" : "강유진",
  "facName" : "SIB",
  "location" : "경기도 수원시 이의동",
  "admCall" : "01087654321",
  "roles" : "ROLE_USER"
}

####
POST http://localhost:8080/account/signup
Content-Type: application/json

{
  "userId" : "sorry",
  "password" : "3",
  "rep" : "김주은",
  "facName" : "인천국제공항",
  "location" : "경기도 수원시 이의동",
  "admCall" : "01087654321",
  "roles" : "ROLE_USER"
}

####
POST http://localhost:8080/account/signin
Content-Type: application/json

{
  "userId" : "hi",
  "password" : "0"
}

