#GET http://localhost:8080/account/checkid/hi
#Accept: application/json
#
####
##POST http://localhost:8080/account/signin
##Content-Type: application/json
##
##{
##  "userId" : "hi",
##  "password" : "0"
##}

#POST http://localhost:8080/container
#Content-Type: application/json
#
#{
#  "height" : 10.0,
#  "length" : 30.0,
#  "releaseDate" : "2023-06-09T18:09",
#  "weight" : 10.0,
#  "weightLimit" : 300.0,
#  "width" : 30.0
#}

GET http://localhost:8080/container/3
Accept: application/json