PUT http://localhost:8080/container/2/palette/1
Content-Type: application/json

{

}
###
POST http://localhost:8080/loadcp
Content-Type: application/json

{
  "containerid" : 2,
  "paletteid" : 1
}

###
GET http://localhost:8080/account/checkid/hi
Accept: application/json

###

POST http://localhost:8080/account/signin
Content-Type: application/json

{
  "userId" : "hi",
  "password" : "0"
}

###

POST http://localhost:8080/container
Content-Type: application/json

{
  "releaseDate" : "2023-06-29T02:19",
  "weight" : 15.0,
  "weightLimit" : 250.0
}

###

GET http://localhost:8080/container?releaseDateFrom=2023-05-28T01:10:00&releaseDateTo=2023-06-03T03:20:00
Accept: application/json

###

POST http://localhost:8080/palette
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJoaSIsInJvbGVzIjpbXSwiaWF0IjoxNjg1ODcwODYzLCJleHAiOjE2ODU4NzE0NjN9.EczCy8u4ip_fatlvj-eHaIxnbN84RakjWkrhMBi0wcQ

{
  "pName": "밥솥",
  "quantity": 150,
  "height": 20.0,
  "weight": 20.0,
  "dLine": "2023-05-30T14:56:10.669",
  "firstDel": "경기도",
  "finalDel": "수원시 영통구"
}

###

GET http://localhost:8080/palette?dLineFrom = 2023-05-23T00:00:20&dLineTo=2023-05-30T23:59:00
Accept: application/json

###

POST http://localhost:8080/account/signup
Content-Type: application/json

{
  "userId" : "hi",
  "password" : "0",
  "adName" : "이영진",
  "department" : "물류팀",
  "position" : "대리",
  "admCall" : "01012345678",
  "roles" : "ROLE_ADMIN"
}

###
POST http://localhost:8080/container
Content-Type: application/json

{
  "releaseDate" : "2023-06-29T02:19",
  "weight" : 5.0,
  "weightLimit" : 40.0
}