#DELETE http://localhost:8080/delete/palette/2
#Content-Type: application/json
#Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJieWUiLCJyb2xlcyI6W10sImlhdCI6MTY4NTkwODExNywiZXhwIjoxNjg1OTA4NzE3fQ.hWY9u5qhdHeu9xWmKw9X4TvTr823rQvpP32CrKfwInI
###

PUT http://localhost:8080/palette/4/container/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJieWUiLCJyb2xlcyI6W10sImlhdCI6MTY4NTkwMDcyNSwiZXhwIjoxNjg1OTAxMzI1fQ.nxCLfOvwIV19VuPYSuNDzv1yc2LFutu6IMeh50FGu9M

{

}
###
POST http://localhost:8080/loadcp
Content-Type: application/json

{
  "containerid" : 2,
  "paletteid" : 1
}

###
GET http://localhost:8080/account/checkid/hi
Accept: application/json

###

POST http://localhost:8080/account/signin
Content-Type: application/json

{
  "userId" : "bye",
  "password" : "1"
}

###

POST http://localhost:8080/container
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJieWUiLCJyb2xlcyI6W10sImlhdCI6MTY4NTg5MTczMywiZXhwIjoxNjg1ODkyMzMzfQ.VJKtErkN5ZlITqDlDU01FT9QW-Lr2Mn6l-dkYwkXUGM

{
  "releaseDate" : "2023-06-29T02:19",
  "weight" : 15.0,
  "weightLimit" : 250.0
}

###

GET http://localhost:8080/container?releaseDateFrom=2023-05-28T01:10:00&releaseDateTo=2023-06-03T03:20:00
Accept: application/json

###

POST http://localhost:8080/palette
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJoaSIsInJvbGVzIjpbXSwiaWF0IjoxNjg1OTAwNjIyLCJleHAiOjE2ODU5MDEyMjJ9.mF57Iea4TbmsBtv80SugYzHMvpNt93xV7dnMz56zXyI

{
  "pName": "전자레인지",
  "quantity": 461,
  "height": 20.0,
  "weight": 20.0,
  "dLine": "2023-05-30T14:56:10.669",
  "firstDel": "경기도",
  "finalDel": "수원시 영통구"
}

###

GET http://localhost:8080/palette?dLineFrom = 2023-05-23T00:00:20&dLineTo=2023-05-30T23:59:00
Accept: application/json

###

POST http://localhost:8080/account/signup
Content-Type: application/json

{
  "userId" : "hi",
  "password" : "0",
  "adName" : "이영진",
  "department" : "물류팀",
  "position" : "대리",
  "admCall" : "01012345678",
  "roles" : "ROLE_ADMIN"
}

###
POST http://localhost:8080/container
Content-Type: application/json

{
  "releaseDate" : "2023-06-29T02:19",
  "weight" : 5.0,
  "weightLimit" : 40.0
}